mysite/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = "accounts"
urlpatterns = [
    url(r'^entrar/$', auth_views.login, {'template_name': 'accounts/login.html'}, name="login"),
    url(r'^cadastro/$', views.register, name="register"),
    url(r'^sair/$', auth_views.logout, {'next_page': 'blog:post_list'}, name="logout"),
]

mysite/blog/urls.py
from django.conf.urls import url
from . import views

app_name = 'blog'
urlpatterns = [
    url(r'^$', views.post_list, name='post_list'),
    url(r'^post/(?P<pk>[0-9]+)/$', views.post_detail, name="post_detail"),
    url(r'^post/new/$', views.post_new, name="post_new"),
    url(r'^post/(?P<pk>[0-9]+)/edit/$', views.post_edit, name='post_edit'),
]

mysite/mysite/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blog.urls')),
    url(r'^conta/', include('accounts.urls')),
]

mysite/accounts/models.py
from django.db import models

# Create your models here.

mysite/blog/models.py
from django.db import models
from django.utils import timezone

class Post(models.Model):
	author = models.ForeignKey('auth.User')
	title = models.CharField(max_length=200)
	text = models.TextField()
	create_date = models.DateTimeField(default=timezone.now)
	published_date = models.DateTimeField(blank=True, null=True)

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.title

mysite/accounts/forms.py
from django import forms

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):

	email = forms.EmailField(label="E-mail")

	def clean_email(self):
		email = self.cleaned_data['email']
		if User.objects.filter(email=email).exists():
			raise forms.ValidationError('Já exite um usuário com este E-mail')
		return email

	def save(self, commit=True):
		user = super(RegisterForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

mysite/blog/forms.py
from django import forms

from .models import Post

class PostForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ('title', 'text',)

mysite/accounts/views.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.conf import settings
from django.shortcuts import render, redirect

from .forms import RegisterForm


def register(request):
	template_name = 'accounts/register.html'
	if request.method == "POST":
		form = RegisterForm(request.POST)
		if form.is_valid():
			user = form.save()
			user = authenticate(username=user.username,
				 password=form.cleaned_data['password1']
			)
			login(request, user)
			return redirect("blog:post_list")
	else:
		form = RegisterForm()
	context = {'form': form}
	return render(request, template_name, context)

mysite/blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone

from .forms import PostForm
from .models import Post

from datetime import datetime

def post_list(request):
    hora = datetime.now().year
    posts = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    context = {
        'posts': posts,
        'hora': hora,
    }
    return render(request, 'blog/post_list.html', context)

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    return render(request, 'blog/post_detail.html', {'post': post})

def post_new(request):
	if request.method == "POST":
		form = PostForm(request.POST)
		if form.is_valid():
			post = form.save(commit=False)
			post.author = request.user
			post.published_date = timezone.now()
			post.save()
			return redirect('blog:post_detail', pk=post.pk)
	else:
		form = PostForm()
	return render(request, 'blog/post_edit.html', {'form': form})

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_edit.html', {'form': form})

mysite/accounts/templates/accounts/login.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>Informe seus dados de cadastro</h1>
    
    <br/>
    <br/>
    <br/>
    
    <form method="POST">
    {% csrf_token %}
        <div style="color: red">
            {{ form.non_field_errors }}
        </div>
        {% for field in form %}
        <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
            <div style="color: red;">
                {{ field.errors }}
            </div>
        </div>
        {% endfor %}
        <button class="btn btn-info btn-large">Entrar</button>

        <br/>
        <br/>

        <p>Não é cadastrado? <a href="{% url 'accounts:register' %}">Cadastre-se</a></p>
        <p>Esqueceu a senha? <a href="">Nova senha</a></p>
    </form>
{% endblock %}

mysite/accounts/templates/accounts/register.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>Informe seus dados</h1>
    
    <br/>
    <br/>
    <br/>
    
    <form method="POST">
    {% csrf_token %}
        <div style="color: red !important;">
            {{ form.non_field_errors }}
        </div>
        {% for field in form %}
        <div class="form-group">
            {{ field.label_tag }}
            {{ field }}
            <div style="color: red !important;">
                {{ field.errors }}
            </div>
        </div>
        {% endfor %}
        <button class="btn btn-info btn-large">Cadastrar</button>

        <br/>
        <br/>

    </form>
{% endblock %}

mysite/blog/templates/blog/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Meu Blog</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link href="https://fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{% static 'css/blog.css' %}">
        <link rel="shortcut icon" href="{% static 'img/rosa-vermelha.jpg' %}" type="image/x-icon" />
    </head>

    <style type="text/css">
        .fundo-preto{
            background-color: #101010;
            padding-top: 5px;
            padding-bottom: 7px;
        }
        .cor-footer{
            color: #fafafa;
        }
        .texto-sombra{
            text-shadow: 2px 2px #101010;
        }
        .page-header ul {
            list-style: none;
        }
        body{
            font-family: 'Open Sans', sans-serif !important;
        }
        body, h1, h2, h3, h4, a, li{
            font-family: 'Open Sans', sans-serif !important;
        }
        .navbar a, li {
            color: #fff;
        }
    </style>

    <body>
        <div class="navbar navbar-fixed-top navbar-inverse">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand scroll" href="{% url 'blog:post_list' %}">Meu blog pessoal</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav navbar-right">
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'accounts:logout' %}">Sair</a></li>
                        {% else %}
                        <li><a href="{% url 'accounts:login' %}">Entrar</a></li>
                        {% endif %}
                        <li><a href=""></a></li>
                        <li><a href="{% url 'blog:post_new' %}">Novo Texto</a></li>
                    </ul>
                </div>
               
            </div>
        </div>
        
        <br/>
        <br/>
        <br/>

        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                {% block content %}
                {% endblock %}
                </div>
                <div class="col-md-4">

                <!-- Blog Search Well -->
                <div class="well">
                    <h4>Blog Search</h4>
                    <div class="input-group">
                        <input type="text" class="form-control">
                        <span class="input-group-btn">
                            <button class="btn btn-default" type="button">
                                <span class="glyphicon glyphicon-search"></span>
                        </button>
                        </span>
                    </div>
                    <!-- /.input-group -->
                </div>

                <!-- Blog Categories Well -->
                <div class="well">
                    <h4>Blog Categories</h4>
                    <div class="row">
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                        <div class="col-lg-6">
                            <ul class="list-unstyled">
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                                <li><a href="#">Category Name</a>
                                </li>
                            </ul>
                        </div>
                        <!-- /.col-lg-6 -->
                    </div>
                    <!-- /.row -->
                </div>

                <!-- Side Widget Well -->
                <div class="well">
                    <h4>Side Widget Well</h4>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Inventore, perspiciatis adipisci accusamus laudantium odit aliquam repellat tempore quos aspernatur vero.</p>
                </div>

            </div>
            </div>
        </div>
        <!-- Page Content -->
    <div class="container">


            <!-- Blog Entries Column -->
            <div class="col-md-8">

                <hr>

                <!-- Pager -->
                <ul class="pager">
                    <li class="previous">
                        <a href="#">&larr; Older</a>
                    </li>
                    <li class="next">
                        <a href="#">Newer &rarr;</a>
                    </li>
                </ul>

            </div>
            <!-- Blog Sidebar Widgets Column -->
    </div>

        <!-- Footer -->
        <footer>
            <div class="row fundo-preto">
                <div class="container">
                    <div class="col-lg-12">
                        <div class="col-lg-6">
                            <h2 class="cor-footer text-left">#SOUEJECT</h2>
                        </div>
                        <div class="col-lg-6">
                            <h2 class="cor-footer text-right">Copyright &copy; Gabriel {{ hora }}</h2>
                        </div>
                    </div>
                <!-- /.col-lg-12 -->
                </div>
            </div>
            <!-- /.row -->
        </footer>

    </div>
    <script type="text/javascript">
        jQuery(document).ready(function($) { 
            $(".scroll").click(function(event){        
                event.preventDefault();
                $('html,body').animate({scrollTop:$(this.hash).offset().top}, 800);
           });
        });
    </script>
    </body>
</html>

mysite/blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
                <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}" ><span class="glyphicon glyphicon-pencil"></span></a>
            </div>
        {% endif %}

        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endblock %}

mysite/blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form">{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-info col-xs-12 col-sm-12 col-md-12 col-lg-12" style="color: #101010">SALVAR</button>
    </form>
{% endblock %}

mysite/blog/templates/blog/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
      
        <div class="post">
            <div class="date">
                {{ post.published_date }}
                <a class="btn btn-default" href="{% url 'blog:post_edit' pk=post.pk %}" ><span class="glyphicon glyphicon-pencil"></span></a>
            </div>
			<h1><a href="{% url 'blog:post_detail' pk=post.pk %}" style="font-family: 'Open Sans', sans-serif !important;">{{ post.title }}</a></h1>
            <p>{{ post.text|linebreaksbr }}</p>
        </div>
        <!--
        <div class="container">
            <div class="col-md-8">
 
                    <h2>
                        <a href="#">{{ post.title }}</a>
                    </h2>
                    <p class="lead">
                        by <a href="index.php">{{ post.author }}</a>
                    </p>
                    <p><span class="glyphicon glyphicon-time"></span>{{ post.published_date }}</p>
                    <hr>
                    <img class="img-responsive" src="http://placehold.it/900x300" alt="">
                    <hr>
                    <p>{{ post.text|linebreaksbr }}</p>
                    <a class="btn btn-primary" href="{% url 'blog:post_detail' pk=post.pk %}">Read More<span class="glyphicon glyphicon-chevron-right"></span></a>

                    <hr>
            </div>
        </div>
        -->
    {% endfor %}
{% endblock content %}